### ISSUE TITLE
Plugin does not work with error

### ISSUE THREAD

**Issue by danielc-salt** [yesinteractive/kong-jwt2header#9]
Hello,
Latest eks and kong ingress controller.

For some reason my eks app does not want to work with the plugin jwt2header.
I get 
```time="2022-12-07T22:44:09Z" level=error msg="could not update kong admin" error="posting new config to /config: HTTP status 400 (message: \"declarative config is invalid: {plugins={[4]={route=\\\"value must be null\\\"}}}\")" subsystem=dataplane-synchronizer```
I am applying at ingress rule, am I doing something wrong:
```apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: jwt2header
config:
  strip_claims: \"true\"
  token_required: \"true\"
plugin: jwt2header```

It should be pretty easy, no?

**Comment by meezaan** [comment]
@danielc-salt The following works for me once the plugin is installed:

```
apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: global-jwt2header
  labels:
    global: "true"
  annotations:
    kubernetes.io/ingress.class: kong
config:
  strip_claims: "false"
  token_required: "false"
plugin: jwt2header
```

By the way, this plugin only runs as global, if I'm not mistaken, so it needs the global label and the annotation for the ingress class.
